### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by Bruce-ywj** [ml4bio/RNA-FM#1]
Can you share the whole data？

**Comment by CKalicki** [comment]
I would like to bump this -- I would also like to have the whole set of training data

**Comment by liusfore** [comment]
I also need this

**Comment by SunQingxu** [comment]
@liusfore    these data you need may be download at  https://proj.cse.cuhk.edu.hk/rnafm/#/download
![image](https://github.com/ml4bio/RNA-FM/assets/63091613/98bd9300-d796-4fe6-962f-a1fd083325df)

**Comment by mydkzgj** [comment]
Hi, Pre-training data is RNAcentral (Release 19, 12/10/2021), while the data for downstream tasks is collected according to their original paper. They can be easily accessed, and you can download them directly based on their corresponding papers.
