### ISSUE TITLE
The difference between RNA-FM-ResNet_bpRNA. pth and RNA-FM-ResNet-RNAStralign.pth

### ISSUE THREAD

**Issue by TimothyChen225** [ml4bio/RNA-FM#11]
thank your great job, I want to know what datasets you used for RNA-FM-ResNet_bpRNA.pth and RNA-FM-ResNet_RNAStralign.pth respectively. I guess you use the TR0 training set to obtain RNA-FM-ResNet_bpRNA.pth and the RNAStralign training set to obtain RNA-FM-ResNet_RNAStralign.pth, Is it right?  If not, could you tell me which dataset these two files were trained on?

**Comment by mydkzgj** [comment]
Exactly. The suffix refers to the dataset used for training, for example, bpRNA and RNAStralign.

**Comment by TimothyChen225** [comment]
Thank you for your reply and clarifications! This has been really helpful for us.
