### ISSUE TITLE
Request an Access to Preprocessed Dataset RNAcentral100

### ISSUE THREAD

**Issue by yukang123** [ml4bio/RNA-FM#6]
Hi Guys! I am curious whether I can access the preprocessed dataset RNAcentral100 which was used to pre-train the foundation model. If not, should I directly download the data from RNAcentral website? https://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/19.0/. 
<img width="1385" alt="image" src="https://github.com/ml4bio/RNA-FM/assets/39018085/aa45ed56-82c7-4203-8753-713d9c3ec5f0">

Thanks a lot!

**Comment by mydkzgj** [comment]
Hi, I think you'd better download it from RNAcentral website directly. It offered a new release with more sequences recently. Then you can process it through cd-hit with your own settings.

**Comment by yukang123** [comment]
Thanks! I do not know cd-hit. Is cd-hit the pre-processing step you took for pertaining. Where can I find the relevant scripts?

**Comment by mydkzgj** [comment]
You can try to follow their manual. https://sites.google.com/view/cd-hit

**Comment by yukang123** [comment]
Got it. I will check it.

**Comment by naimavahab** [comment]
can you please provide the cd-hit-est command used for cleaning the rnacentral dataset ? And an estimate of the hardware and time it consumed?
